### ISSUE TITLE
Weights not totalling 100

### ISSUE THREAD

**Issue by coonwhiz** [tcprescott/sahasrahbot#18]
In the new pogchampion preset for alttpr, the hints on lines 59 and 124 total to 103 rather than 100.
![image](https://user-images.githubusercontent.com/35547745/91766063-94fa9900-eb9f-11ea-8389-911492b430e9.png)

**Comment by tcprescott** [comment]
Hi, thanks for the report.

It isn't a requirement that the weights add up to 100.  Also, these weights are specified by the winner of a tournament, so they'll need to tell me to update it.  I will forward this observation to them though.

-Synack
